### PR TITLE
Release 0.3.0

### PR DESCRIPTION
**Pull request by rhpvorderman**
### Checklist
- [ ] Pull request details were added to CHANGELOG.rst
- [ ] Documentation was updated (if needed)

### CODE REVIEW

**Comment by bdraco** [comment]
Many thanks.  Tested and its even faster 🚀

**Comment by rhpvorderman** [comment]
If you want speed, please also checkout [python-isal](https://github.com/pycompression/python-isal). I maintain that library too.

**Comment by bdraco** [comment]
Thanks. Will give it a try. 🤞 that its compatible enough that this works : https://github.com/bdraco/aiohttp-zlib-ng/blob/6bc09cce7916492b1ab389cfc865f09d83a22c64/src/aiohttp_zlib_ng/__init__.py#L20

**Comment by bdraco** [comment]
Seems to work great. Will fallback to `zlib_ng` on the old RPIs. Thanks for the tip

**Pull request merged**
