### PR TITLE
Update zlib-ng to 2.1.5

### PR DESCRIPTION
**Pull request by bdraco**
### Checklist
- [x] Pull request details were added to CHANGELOG.rst
- [x] Documentation was updated (if needed)

### CODE REVIEW

**Comment by rhpvorderman** [comment]
I am currently waiting for some changes in python-isal to shake out. Currently multithreaded solutions are added. I plan to port these to python-zlib-ng and make a new release then.

**Comment by bdraco** [comment]
Great.  Let me know if there is anything you need tested.


Thanks!

**Comment by bdraco** [comment]
@rhpvorderman Any chance you can take a look at this sooner as it looks like the old zlib-ng version is causing problems with older CPUs in https://github.com/home-assistant/core/issues/105254 ?

Thanks!

**Comment by rhpvorderman** [comment]
Sure. I just merged #21 with the version bump and some other commits. I will try to make a release today, also to get the BSD patch in.

**Comment by bdraco** [comment]
Thank you!

**Pull request closed without merging**
